"""Initial migration

Revision ID: 597d9e44a82c
Revises: d9ada1735366
Create Date: 2024-01-25 01:19:56.210335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '597d9e44a82c'
down_revision: Union[str, None] = 'd9ada1735366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('like', sa.Boolean(), nullable=True))
    op.drop_column('votes', 'mark')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('mark', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('votes', 'like')
    # ### end Alembic commands ###
