"""Initial migration

Revision ID: 89eb4cac3e9c
Revises: 1f1966f4e40f
Create Date: 2024-01-25 00:12:24.610221

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '89eb4cac3e9c'
down_revision: Union[str, None] = '1f1966f4e40f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('vote', sa.Boolean(), nullable=True))
    op.drop_column('posts', 'rating_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('rating_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'vote')
    # ### end Alembic commands ###
