"""Initial migration

Revision ID: b6b46e3e7203
Revises: 129060f920b5
Create Date: 2024-01-25 00:59:33.473634

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b6b46e3e7203'
down_revision: Union[str, None] = '129060f920b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'vote')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('vote', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
