"""Initial migration

Revision ID: d9ada1735366
Revises: 0fcd4f6673cb
Create Date: 2024-01-25 01:09:20.026285

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd9ada1735366'
down_revision: Union[str, None] = '0fcd4f6673cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('mark', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'mark')
    # ### end Alembic commands ###
